### ISSUE TITLE
Go 1.21.x CI runs on 1.22 version

### ISSUE THREAD

**Issue by shan-96** [ksysoev/wasabi#107]
I found a problem while running CI on GH actions.
It seem the 1.21.x pipeline is also running on 1.22.

![image](https://github.com/ksysoev/wasabi/assets/16632302/bfea6e56-c34f-42b9-90a4-11a90c7aebd3)

**Comment by ksysoev** [comment]
@shan-96 interesting, it looks like a but in `actions/setup-go@v3`,  let try to investigate it next week

**Comment by ksysoev** [comment]
Wait, problem in `go.mod`, it was bumped to 1.22 and setup go look to be taking version from there. let me check if package still able to run on 1.21

**Comment by shan-96** [comment]
@ksysoev I think the problem came from
```
go mod tidy
```
because there are some standard libraries used in source that are incompatible with 1.21.x
for example
```
"golang.org/x/exp/slog"
```

**Comment by ksysoev** [comment]
Yeah, you're right, we can drop 1.21

**Comment by ksysoev** [comment]
1.21 is removed
