### ISSUE TITLE
Improve server_test 

### ISSUE THREAD

**Issue by KianYang-Lee** [ksysoev/wasabi#59]
Current `server_test` package contains test that relies on `time.Sleep` to wait server to be ready for accepting connection. Hope to refactor these test to use the `ready` channel of server for better readability. I can open a PR to refactor these tests

**Comment by ksysoev** [comment]
@KianYang-Lee could you give a link to test you mean, I see only protection selects that help us to not wait forever on a signal and fail test faster

**Comment by KianYang-Lee** [comment]
@ksysoev for example this https://github.com/ksysoev/wasabi/blob/main/server/server_test.go#L85-L117 . We can just wait on `ready` chan . Makes for better readability

**Comment by KianYang-Lee** [comment]
let me make a PR and you can see better

**Comment by ksysoev** [comment]
implemented in #62
