### ISSUE TITLE
Add support to use custom configuration

### ISSUE THREAD

**Issue by shan-96** [ksysoev/wasabi#68]
~- Choose what sort of config files to use~
~- load config in memory~ use BaseContext
~- provide proper context to flow the configs everywhere~
- Ensure server's base context has server specific mandatory configs

@ksysoev let me know your thoughts

**Comment by ksysoev** [comment]
@shan-96 in terms of context flow I think it already can be done with current implementation.

Server abstraction provides possibility to set base context for  every http request. 
https://github.com/ksysoev/wasabi/blob/main/server/server.go#L180-L188

we can set a value on based context and it'll be available in every request.

basically based context is used for every http request, and latter we take http request context and use it as connection context here

https://github.com/ksysoev/wasabi/blob/main/channel/channel.go#L68-L83

and later we should be  using this context for request creation https://github.com/ksysoev/wasabi/blob/main/examples/http_backend/main.go#L34 
(maybe we should keep it at client side to taka context from connection and instead move this logic to dispatcher)

**Comment by shan-96** [comment]
>but providing some helpers for more convenient way to work context could be an option here, kind of typed selectors to retrieve values from configuration that stored in context.

Agree with this, we should not pursue config parsing if the idea is to always rely on dispatcher or client to populate the context
