### ISSUE TITLE
Replace naive implementation of circuit breaker with using proper library 

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/wasabi#77]
Current implementation of circuit breaker midleware is quite naive and not implementing pattern properly, it would be nice to replace it with properly implemented library.

this could be a good candidate for the replacement:
 https://github.com/sony/gobreaker

**Comment by KianYang-Lee** [comment]
the existing param `recoverAfter` for `NewCircuitBreakerMiddleware` is not able to integrate with this library. We can only control how the CB turns semi-open with duration, not number of successful requests. Anyhow when the CB is open it will not allow requests anyway, so there is no way to hit the condition?

**Comment by ksysoev** [comment]
@KianYang-Lee sure feel free to drop `recoverAfter` parameter
