### ISSUE TITLE
Add possibility to define weight for nodes in load balancer logic

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/wasabi#91]
In current implementation all backends are considered to be equal, and balanser will try to distribute load equally across all of them.
In real production environment it could be possible that some nodes may have to have more resources than other. For such cases we should be able to provide possibility define node weight.

load should work as follows, if node weight is 2 it should be handling twice more request to compare to node with weight 1.

**Comment by ksysoev** [comment]
this probably better to define through policy, rather try to fit into current algorithm.

**Comment by shan-96** [comment]
@ksysoev we can close this
