### ISSUE TITLE
Predicate for retry middleware

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/wasabi#94]
Not every error make sense to retry, it would be nice to provide possibility to provide optional predicate that will check if error need to be retried or not.

Usually only transient errors worth to be retried, if error is not recoverable doesn't make to spend resources and client's time on retries.

**Comment by KianYang-Lee** [comment]
@ksysoev can I take this over?

**Comment by ksysoev** [comment]
Sure go ahead
