### ISSUE TITLE
Redefine backoff strategy for retry middleware

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/wasabi#95]
Current implementation of retry middleware use equals intervals between retries. It may be useful to have possibility to redefine policy for retry intervals.

probably we can accept optional argument with a function that will accept 2 parameters with current retry counter and initial retry interval, based on these parameters function should calculate interval that needs to be awaited.

**Comment by shan-96** [comment]
@ksysoev can I take this over? Also I think I don't need to wait for #94 to finish to begin this.

**Comment by ksysoev** [comment]
@shan-96 sure
